version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: project_name
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  pgdata:
